//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortLog.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOProducto", Namespace="http://schemas.datacontract.org/2004/07/WcfServicePortLog1")]
    [System.SerializableAttribute()]
    public partial class DTOProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dominio.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PesoUnidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dominio.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PesoUnidad {
            get {
                return this.PesoUnidadField;
            }
            set {
                if ((this.PesoUnidadField.Equals(value) != true)) {
                    this.PesoUnidadField = value;
                    this.RaisePropertyChanged("PesoUnidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerProductos", ReplyAction="http://tempuri.org/IService1/TraerProductosResponse")]
        PortLog.ServiceReference1.DTOProducto[] TraerProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerProductos", ReplyAction="http://tempuri.org/IService1/TraerProductosResponse")]
        System.Threading.Tasks.Task<PortLog.ServiceReference1.DTOProducto[]> TraerProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AltaImportacion", ReplyAction="http://tempuri.org/IService1/AltaImportacionResponse")]
        bool AltaImportacion(int cantidad, System.DateTime fechaIngreso, System.DateTime fechaSalidaPrevista, int idProd, decimal precioProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AltaImportacion", ReplyAction="http://tempuri.org/IService1/AltaImportacionResponse")]
        System.Threading.Tasks.Task<bool> AltaImportacionAsync(int cantidad, System.DateTime fechaIngreso, System.DateTime fechaSalidaPrevista, int idProd, decimal precioProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PortLog.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PortLog.ServiceReference1.IService1>, PortLog.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PortLog.ServiceReference1.DTOProducto[] TraerProductos() {
            return base.Channel.TraerProductos();
        }
        
        public System.Threading.Tasks.Task<PortLog.ServiceReference1.DTOProducto[]> TraerProductosAsync() {
            return base.Channel.TraerProductosAsync();
        }
        
        public bool AltaImportacion(int cantidad, System.DateTime fechaIngreso, System.DateTime fechaSalidaPrevista, int idProd, decimal precioProducto) {
            return base.Channel.AltaImportacion(cantidad, fechaIngreso, fechaSalidaPrevista, idProd, precioProducto);
        }
        
        public System.Threading.Tasks.Task<bool> AltaImportacionAsync(int cantidad, System.DateTime fechaIngreso, System.DateTime fechaSalidaPrevista, int idProd, decimal precioProducto) {
            return base.Channel.AltaImportacionAsync(cantidad, fechaIngreso, fechaSalidaPrevista, idProd, precioProducto);
        }
    }
}
